spring:
  application:
    name: task-list
  datasource:
    url: jdbc:postgresql://localhost:5434/tasklist?currentSchema=tasklist
    username: mark
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8888
security:
  jwt:
    secret: Zmhid2Z1MzIzMjc4dDRnM2loZmlvMTJvam9pSkRGMTI4M1I4OTFPSEZKRElXSkVGMjE5ODBIRlc=
    access: 360000
    refresh: 2592000000
